name: Auto-Deploy on Commit

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Select branch to deploy (Dev or Test)"
        required: true
        default: "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and branches

      - name: Set Target Branch
        run: |
          TARGET_BRANCH=${{ github.event.inputs.target_branch }}
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV
          echo "Selected target branch: $TARGET_BRANCH"

      - name: Ensure Target Branch Exists
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/$TARGET_BRANCH; then
            echo "Branch $TARGET_BRANCH exists."
          else
            echo "Branch $TARGET_BRANCH does not exist. Creating..."
            git checkout -b $TARGET_BRANCH
            git push origin $TARGET_BRANCH
          fi
