name: Auto-Deploy on Commit

on:
  push:
    branches:
      - master  # Trigger workflow when master branch is updated
  workflow_dispatch:  # Enables manual trigger (blue popup)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Target Branch
        id: set_branch
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          
          # Logic to decide target branch
          if [[ "$COMMIT_MSG" == *"[deploy-test]"* ]]; then
            TARGET_BRANCH="Test"
          else
            TARGET_BRANCH="Dev"
          fi
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV
          echo "Target branch set to: $TARGET_BRANCH"

      - name: Checkout Target Branch
        run: |
          git fetch origin $TARGET_BRANCH
          git checkout -B $TARGET_BRANCH origin/$TARGET_BRANCH

      - name: Pull Latest Changes
        run: |
          git pull origin $TARGET_BRANCH --rebase || echo "No changes to rebase"

      - name: Create/Update Notepad File
        run: |
          echo "Welcome to GitHub Actions in $TARGET_BRANCH branch" > welcome.txt
          cat welcome.txt  # Verify content

      - name: Commit Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add welcome.txt
          git commit -m "Updated welcome.txt from master commit" || echo "No changes to commit"

      - name: Push Changes to Target Branch
        run: |
          git push origin $TARGET_BRANCH
