name: Auto-Deploy on Commit

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Select branch to deploy (Dev or Test)"
        required: true
        default: "Dev"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and branches

      - name: Set Target Branch
        run: |
          TARGET_BRANCH=${{ github.event.inputs.target_branch }}
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV
          echo "Selected target branch: $TARGET_BRANCH"
      - name: Ensure Target Branch Exists
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/$TARGET_BRANCH; then
            echo "Branch $TARGET_BRANCH exists."
          else
            echo "Branch $TARGET_BRANCH does not exist. Creating..."
            git checkout -b $TARGET_BRANCH
            git push origin $TARGET_BRANCH
          fi
      - name: Checkout Target Branch
        run: |
          git checkout $TARGET_BRANCH
      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "Welcome to GitHub Actions in $TARGET_BRANCH branch" > welcome.txt
          git add welcome.txt
          git commit -m "Updated welcome.txt from $TARGET_BRANCH branch" || echo "No changes to commit"
          git push origin $TARGET_BRANCH

