name: Auto-Deploy on Commit

on:
  push:
    branches:
      - master  # Only trigger when changes happen in master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get the Branch Name
      run: echo "Deploying changes from $GITHUB_REF_NAME to branch..."

    - name: Checkout Repository (master Branch)
      uses: actions/checkout@v3
      with:
        ref: master  # Always checkout Test branch

    - name: Pull latest changes
      run: |
        git pull origin master --rebase  # Pull latest changes before modifying files

    - name: Create Notepad File
      run: |
        echo "Welcome to GitHub Actions" > welcome.txt  # Create welcome.txt
        echo "Welcome to GitHub Actions (Harikaran2209) in master" > welcome.txt  # Create welcome.txt
        cat welcome.txt  # Verify content

    - name: Commit Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add welcome.txt
        git commit -m "Added welcome.txt from master branch commit" || echo "No changes to commit"

    - name: Push Changes to master Branch
      run: |
        git push origin master
