name: Auto-Deploy on Commit

on:
  push:
    branches:
      - master
      - Dev
      - Test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get the Branch Name
      run: echo "Deploying changes from $GITHUB_REF_NAME to Dev branch..."

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: Dev  # Always checkout Dev branch

    - name: Pull latest changes
      run: |
        git pull origin Dev --rebase  # Pull latest changes before modifying files

    - name: Modify the Branch
      run: |
        echo "Working in Dev branch"
        cat index.html
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "File changes from $GITHUB_REF_NAME -> Dev" || echo "No changes to commit"

    - name: Push Changes to Dev Branch
      run: |
        git push origin Dev
