name: Deploy to EC2 with Temporary Security Group

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get GitHub Runner Public IP
        run: |
          PUBLIC_IP=$(curl -s https://checkip.amazonaws.com)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
        shell: bash

      - name: Create Security Group
        run: |
          SECURITY_GROUP_ID=$(aws ec2 create-security-group \
            --group-name "github-actions-sg-$(date +%s)" \
            --description "Temporary SG for GitHub Actions Deployment" \
            --vpc-id $(aws ec2 describe-vpcs --query "Vpcs[0].VpcId" --output text) \
            --query "GroupId" --output text)

          echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> $GITHUB_ENV

          aws ec2 authorize-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ env.PUBLIC_IP }}/32

          echo "Temporary Security Group Created: $SECURITY_GROUP_ID"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        shell: bash

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts
        shell: bash

      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} "echo Connected Successfully"
        shell: bash

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu
            git clone https://github.com/Harikaran2209/Actions.git || (cd Actions && git pull)
            cd Actions
            cat welcome.txt  # Run deployment script if applicable
          EOF
        shell: bash

      - name: Delete Temporary Security Group
        if: always()
        run: |
          aws ec2 delete-security-group --group-id ${{ env.SECURITY_GROUP_ID }}
          echo "Temporary Security Group Deleted: ${{ env.SECURITY_GROUP_ID }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        shell: bash
