name: Protect Config File Workflow

on:
  push:
    branches:
      - master
    paths:
      - 'Actions/config.json'
  workflow_dispatch:  # Manual trigger support

jobs:
  protect-config:
    name: Protect config.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0  # Important!

      - name: Check if config.json was modified (for push trigger)
        if: github.event_name == 'push'
        id: check_diff
        run: |
          git fetch origin
          if git diff HEAD~1 HEAD --name-only | grep Actions/config.json; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip revert if file not changed (only for push)
        if: github.event_name == 'push' && steps.check_diff.outputs.changed != 'true'
        run: echo "config.json not modified, skipping revert."

      - name: Revert config.json (both push/manual)
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && steps.check_diff.outputs.changed == 'true')
        run: |
          git checkout origin/master -- Actions/config.json
          git config user.name "config-protect-bot"
          git config user.email "bot@example.com"
          git commit --allow-empty -m "Auto-revert config.json to protected state"
          git push origin master 
