on:
  push:
    branches:
      - master
    paths:
      - 'config.json'
  workflow_dispatch:

jobs:
  protect-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Check if config.json was modified (for push trigger)
        if: github.event_name == 'push'
        id: check_diff
        run: |
          git fetch origin
          if git diff HEAD~1 HEAD --name-only | grep config.json; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Revert config.json (both push/manual)
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && steps.check_diff.outputs.changed == 'true')
        run: |
          git checkout origin/master -- config.json
          git config user.name "config-protect-bot"
          git config user.email "bot@example.com"
          git commit --allow-empty -m "Auto-revert config.json to protected state"
          git push origin master
